name: 2yoursuccess.nl
favicon: null
layout_spectrum: 0.5699497505556792
typography_spectrum: 0.2988843859639019
title: Ultimate Coaching
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8532442154828459
  lightness: 0.01685036043636501
  saturation: 0.875
  rhythmicContrast: 0.7216745459008962
purpose: []
