name: 2yoursuccess.nl
favicon: null
layout_spectrum: 0.5699497505556792
typography_spectrum: 0.2988843859639019
title: Ultimate Coaching
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070606'
    - '#3a3b3b'
    - '#c1c1c1'
    - '#8f8f8f'
    - '#f14435'
  brandStrength: 0.8532442154828459
  lightness: 0.01685036043636501
  saturation: 0.875
  rhythmicContrast: 0.7216745459008962
purpose: []
